#!/bin/sh
cd /home/cappittall/Documents/Said/django_instagram2
source ./myenv/bin/activate
export DJANGO_SETTINGS_MODULE=core.settings
#python manage.py makemigrations api
#python manage.py migrate
daphne -b 0.0.0.0 -p 8000 core.asgi:application 

