# Generated by Django 3.2 on 2023-02-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='service',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
