# Generated by Django 4.1.5 on 2023-02-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_orderlist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='remains',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
