# Generated by Django 3.2 on 2023-02-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_orderlist_remains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccounts',
            name='country_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='instagramaccounts',
            name='followers_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
