# Generated by Django 3.2 on 2023-02-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230214_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccounts',
            name='error',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
