# Generated by Django 3.2 on 2023-02-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_instagramaccounts_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramVersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='0.0.0', max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Instagram Version',
                'ordering': ('-id',),
            },
        ),
    ]
