# Generated by Django 3.2 on 2023-02-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_instagramversions'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccounts',
            name='bot_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagramaccounts',
            name='default_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profil',
            name='coin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
