# Generated by Django 3.2 on 2023-02-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230224_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccounts',
            name='default_user',
            field=models.BooleanField(default=True),
        ),
    ]
