# Generated by Django 4.1.5 on 2023-02-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_instagramaccounts_default_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='insta_start_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
