# Generated by Django 3.2 on 2023-03-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_orderlist_insta_start_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccounts',
            name='claim',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instagramaccounts',
            name='csrftoken',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='instagramaccounts',
            name='ds_user_id',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='instagramaccounts',
            name='mid',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='instagramaccounts',
            name='pwd_password',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instagramaccounts',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
