# Generated by Django 3.2 on 2023-03-06 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('api', '0011_auto_20230306_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='packpages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packpage', to='services.userpackpages', verbose_name='Kullanıcı Paketi'),
        ),
    ]
