# Generated by Django 3.2 on 2023-02-09 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=250, verbose_name='Type')),
            ],
            options={
                'verbose_name_plural': 'Servis Type',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CountryCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ülke Kodu')),
            ],
            options={
                'verbose_name_plural': 'Ülke Kodları',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, verbose_name='Cinsiyet')),
            ],
            options={
                'verbose_name_plural': 'Cinsiyetler',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HostKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=0, max_length=50, verbose_name='API-KEY')),
                ('host', models.CharField(max_length=150, verbose_name='Sağlayıcı')),
                ('creatdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, verbose_name='Kategori')),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.categorytype', verbose_name='Type')),
            ],
            options={
                'verbose_name_plural': 'Servis Kategorileri',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesSuccessfulLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=100, verbose_name='servis id')),
                ('service_name', models.CharField(max_length=500, verbose_name='Servis Adı')),
                ('successful_value', models.IntegerField(default=0, verbose_name='Başarılı İşlem Sayısı')),
            ],
            options={
                'verbose_name_plural': 'Başarılı İşlem Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='UserPackpages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Paket Adı')),
                ('category', models.ManyToManyField(blank=True, to='user.UsersCategories')),
                ('country_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.countrycodes', verbose_name='Ülke Kodu')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.genders', verbose_name='Cinsiyet')),
            ],
            options={
                'verbose_name_plural': 'Kullanıcı Paketleri',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Servis İsmi')),
                ('rate', models.FloatField(default=150.0, verbose_name='Fiyat')),
                ('min', models.IntegerField(default=0, verbose_name='min')),
                ('max', models.IntegerField(default=0, verbose_name='max')),
                ('dripfeed', models.BooleanField(default=False, verbose_name='dripfeed')),
                ('refill', models.BooleanField(default=True, verbose_name='refill')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory', verbose_name='Kategori')),
                ('packpages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.userpackpages', verbose_name='Kullanıcı Paketi')),
            ],
            options={
                'verbose_name_plural': 'Servisler',
                'ordering': ['-service'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.FloatField(default=0, verbose_name='charge')),
                ('start_count', models.IntegerField(default=0, verbose_name='start_count')),
                ('status', models.CharField(max_length=50, verbose_name='status')),
                ('remains', models.IntegerField(default=0, verbose_name='remains')),
                ('currency', models.CharField(max_length=10, verbose_name='currency')),
                ('successful_value', models.IntegerField(default=0, verbose_name='Başarılı İşlem Miktarı')),
                ('process', models.IntegerField(default=0, verbose_name='İşlem Sayısı')),
                ('cancelled', models.BooleanField(default=False, verbose_name='İptal Durumu')),
                ('target', models.CharField(max_length=500, verbose_name='Hedef')),
                ('user_order', models.BooleanField(default=False, verbose_name='Kullanıcı Siparişi')),
                ('auto_process', models.BooleanField(default=False, verbose_name='Oto İşlem')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.services', verbose_name='service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=0, max_length=50, verbose_name='API-KEY')),
                ('creatdate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
        ),
        migrations.CreateModel(
            name='Affirmations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.TextField(blank=True, null=True, verbose_name='Hedef Kullanıcılar')),
                ('target_user', models.CharField(blank=True, max_length=250, null=True, verbose_name='target_user')),
                ('users_value', models.IntegerField(default=0, verbose_name='Hedef Kullanıcı Sayısı')),
                ('media_link', models.CharField(max_length=500, verbose_name='Media Link')),
                ('message1', models.TextField(verbose_name='Media Mesajı')),
                ('link', models.CharField(max_length=500, verbose_name='Link')),
                ('message2', models.TextField(verbose_name='Link Mesajı')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('user_follower_scanner', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.orders', verbose_name='order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services', verbose_name='service')),
            ],
            options={
                'verbose_name_plural': 'Api Sipariş Onaylamaları',
                'ordering': ['id'],
            },
        ),
    ]
