# Generated by Django 3.2 on 2023-03-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_newuserpackpages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUserPackpages',
        ),
    ]
