# Generated by Django 3.2 on 2023-03-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_delete_newuserpackpages'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackpages',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userpackpages',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userpackpages',
            name='subLocality',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
