# Generated by Django 3.2 on 2023-02-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('explanation', models.CharField(max_length=1000, verbose_name='Açıklama')),
                ('button1', models.CharField(max_length=100, verbose_name='button 1 ismi')),
                ('button2', models.CharField(max_length=100, verbose_name='button 2 ismi')),
                ('button1_link', models.CharField(max_length=500, verbose_name='button 1 link')),
                ('button2_link', models.CharField(max_length=500, verbose_name='button 2 link')),
            ],
            options={
                'verbose_name_plural': 'Anasayfa İçeriği',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LoginQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('process', models.IntegerField(default=0, verbose_name='İşlem Sayısı')),
                ('end', models.BooleanField(default=False, verbose_name='Bitiş Durumu')),
            ],
            options={
                'verbose_name_plural': 'Instagram Giriş Sırası',
                'ordering': ['-date'],
            },
        ),
    ]
