# Generated by Django 3.2 on 2023-02-09 07:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='İçerik')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AutoFollowUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Kullanıcı Adı')),
                ('quantity', models.IntegerField(default=0, verbose_name='Beğeni Miktarı')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Emir Tarihi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.orders', verbose_name='order')),
            ],
            options={
                'verbose_name_plural': 'Oto Follow Kullanıcılar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AutoLikeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Kullanıcı Adı')),
                ('quantity', models.IntegerField(default=0, verbose_name='Beğeni Miktarı')),
                ('timeout', models.IntegerField(default=0, verbose_name='Emir Süresi (Gün)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Emir Tarihi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.orders', verbose_name='order')),
            ],
            options={
                'verbose_name_plural': 'Oto Post Beğeni Kullanıcılar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ImportFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_data', verbose_name='Dosya')),
            ],
            options={
                'verbose_name_plural': 'Kullanıcı Import Dosyaları',
            },
        ),
        migrations.CreateModel(
            name='MailSMTPInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL_HOST', models.CharField(max_length=100, verbose_name='Email Host')),
                ('EMAIL_PORT', models.IntegerField(default=0, verbose_name='Email Port')),
                ('EMAIL_HOST_USER', models.CharField(max_length=100, verbose_name='EMAIL_HOST_USER(Email)')),
                ('EMAIL_HOST_PASSWORD', models.CharField(max_length=100, verbose_name='EMAIL_HOST_PASSWORD(Password)')),
            ],
            options={
                'verbose_name_plural': 'Mail SMTP Bilgileri',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Mentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootfile', models.FileField(upload_to='mentionlogs', verbose_name='Dosya')),
                ('status', models.BooleanField(default=False, verbose_name='Durum')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
            options={
                'verbose_name_plural': 'Mention Kontrol Kayıtları',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NotLoginUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=250, null=True, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'Giriş Yapamayan Kullanıcılar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(max_length=1000, verbose_name='Proxy')),
                ('ip_port_proxy', models.BooleanField(default=False, verbose_name='İp Port Proxy')),
                ('auth_proxy', models.BooleanField(default=False, verbose_name='Şifreli Proxy')),
                ('login_after_proxy', models.BooleanField(default=False, verbose_name='Login Öncesi Proxy')),
                ('login_proxy', models.BooleanField(default=False, verbose_name='Login Proxy')),
                ('process_proxy', models.BooleanField(default=False, verbose_name='İşlem Proxy')),
                ('auto_process_proxy', models.BooleanField(default=False, verbose_name='Oto İşlem Proxy')),
                ('video_proxy', models.BooleanField(default=False, verbose_name='Video İzleme Proxy')),
            ],
            options={
                'verbose_name_plural': 'Proxyler',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_tag', models.CharField(max_length=100, verbose_name='google tag kodu')),
                ('ana_title', models.CharField(max_length=1000, verbose_name='site başlığı')),
                ('description', models.CharField(max_length=1000, verbose_name='description, açıklama')),
                ('keywords', models.CharField(max_length=1000, verbose_name='keywords , anahtar kelimeler')),
                ('site_logo', models.ImageField(upload_to='', verbose_name='Site Logo')),
                ('admin_logo', models.ImageField(upload_to='', verbose_name='Admin Logo')),
                ('fav_icon', models.ImageField(upload_to='', verbose_name='Fav İcon')),
                ('proxy_limit', models.IntegerField(default=1, verbose_name='Proxy anlık işlem limiti ')),
                ('proxy_limit_video', models.IntegerField(default=1, verbose_name='Video izleme thread limiti ')),
                ('proxy_limit_login', models.IntegerField(default=1, verbose_name='User ekleme thread limiti ')),
                ('user_balance', models.IntegerField(default=0, verbose_name='Kullanıcı Kredi Yenileme Miktarı ')),
                ('user_logins', models.BooleanField(default=True, verbose_name='Dışarıdan instagram kullanıcı Girişleri')),
                ('process_queue_disabled', models.BooleanField(default=False, verbose_name='İşlem Sırasını Devre Dışı Bırak')),
            ],
            options={
                'verbose_name_plural': 'Seo ve Genel ayarlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UsersScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootfile', models.FileField(upload_to='usersscannerlogs', verbose_name='Dosya')),
                ('status', models.BooleanField(default=False, verbose_name='Durum')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
            options={
                'verbose_name_plural': 'Kullanıcı Tarama Kayıtları',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VideoSayacLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayac_value', models.IntegerField(default=0, verbose_name='sayac value')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.orders', verbose_name='order')),
            ],
        ),
        migrations.CreateModel(
            name='GetFollowDataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, verbose_name='Username')),
                ('users_list_username', models.TextField(default='', verbose_name='Kullanıcı Listesi Username')),
                ('users_list_user_id', models.TextField(default='', verbose_name='Kullanıcı Listesi User Id')),
                ('success', models.BooleanField(default=False, verbose_name='Tamamlanma Durumu')),
                ('cancelled', models.BooleanField(default=False, verbose_name='İptal Durumu')),
                ('sending_mail', models.BooleanField(default=False, verbose_name='Sistem Tarafından Mail Gönderilme Durumu')),
                ('usersValue', models.IntegerField(default=0, verbose_name='Çekin Takipçi Sayısı')),
                ('api_contact_mail', models.CharField(blank=True, max_length=250, null=True, verbose_name='Api Siparişi İletişim Maili')),
                ('date', models.DateField(auto_now_add=True)),
                ('api_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.orders', verbose_name='API Order')),
            ],
            options={
                'verbose_name_plural': 'Kullanıcı Takipçilerini Getirme',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AutoLikeUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=250, verbose_name='post media id')),
                ('auto_like_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.autolikeuser', verbose_name='Auto Like')),
            ],
            options={
                'verbose_name_plural': 'Oto Post Beğeni Kullanıcı Log',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AutoLikeQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, verbose_name='Oto Beğeni İşlem Sırası')),
                ('successful_value', models.IntegerField(default=0, verbose_name='Başarılı İşlem')),
                ('media_id', models.CharField(max_length=250, verbose_name='post media id')),
                ('auto_like_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.autolikeuser', verbose_name='Auto Like')),
            ],
            options={
                'verbose_name_plural': 'Oto Post Beğeni İşlem Sırası',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AutoFollowUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, verbose_name='user_id')),
                ('username', models.CharField(max_length=250, verbose_name='Kullanıcı Adı')),
                ('auto_follow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.autofollowuser', verbose_name='Auto Like')),
            ],
            options={
                'verbose_name_plural': 'Oto Follow Kullanıcı Log',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AutoFollowQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, verbose_name='Oto Follow İşlem Sırası')),
                ('successful_value', models.IntegerField(default=0, verbose_name='Başarılı İşlem')),
                ('target_user', models.CharField(max_length=250, verbose_name='hedef user')),
                ('auto_follow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.autofollowuser', verbose_name='Auto Follow')),
            ],
            options={
                'verbose_name_plural': 'Oto Follow İşlem Sırası',
                'ordering': ['-id'],
            },
        ),
    ]
