# Generated by Django 3.2 on 2023-03-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSettingsNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_tag', models.CharField(max_length=100, verbose_name='google tag kodu')),
                ('site_title', models.CharField(max_length=1000, verbose_name='site başlığı')),
                ('description', models.CharField(max_length=1000, verbose_name='description, açıklama')),
                ('keywords', models.CharField(max_length=1000, verbose_name='keywords , anahtar kelimeler')),
                ('play_store_link', models.CharField(max_length=250, verbose_name='Play Store Linki')),
                ('site_message', models.CharField(max_length=1000, verbose_name='Site Sol Mesaj')),
                ('twitter_link', models.CharField(max_length=250, verbose_name='Twitter Linki')),
                ('facebook_link', models.CharField(max_length=250, verbose_name='Facebook Linki')),
                ('instagram_link', models.CharField(max_length=250, verbose_name='Instagram Linki')),
            ],
            options={
                'verbose_name_plural': 'Seo ve Genel ayarlar (Yeni)',
                'ordering': ['-id'],
            },
        ),
    ]
