# Generated by Django 3.2 on 2023-03-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_seosettingsnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettingsnew',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marka/Şirket Adı'),
        ),
        migrations.AlterField(
            model_name='seosettingsnew',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='description, açıklama'),
        ),
        migrations.AlterField(
            model_name='seosettingsnew',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Facebook Linki'),
        ),
        migrations.AlterField(
            model_name='seosettingsnew',
            name='google_tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='google tag kodu'),
        ),
        migrations.AlterField(
            model_name='seosettingsnew',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Instagram Linki'),
        ),
        migrations.AlterField(
            model_name='seosettingsnew',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='keywords , anahtar kelimeler'),
        ),
        migrations.AlterField(
            model_name='seosettingsnew',
            name='play_store_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Play Store Linki'),
        ),
        migrations.AlterField(
            model_name='seosettingsnew',
            name='site_message',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Site Sol Mesaj'),
        ),
        migrations.AlterField(
            model_name='seosettingsnew',
            name='site_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='site başlığı'),
        ),
        migrations.AlterField(
            model_name='seosettingsnew',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Twitter Linki'),
        ),
    ]
