# Generated by Django 3.2 on 2023-03-07 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_admin', '0003_auto_20230307_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Kod')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefon (Ülke Kodu İle Birlikte)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('remaining', models.IntegerField(default=3, verbose_name='Kalan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'SMS Onay Kodları',
                'ordering': ['-date'],
            },
        ),
    ]
