# Generated by Django 3.2 on 2023-03-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_smsloginlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsloginlog',
            name='phone',
        ),
    ]
