# Generated by Django 3.2 on 2023-03-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_remove_smsloginlog_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsloginlog',
            name='ip',
            field=models.CharField(default='afd', max_length=50, verbose_name='ip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsloginlog',
            name='session_id',
            field=models.CharField(default='afd', max_length=100, verbose_name='session_id'),
            preserve_default=False,
        ),
    ]
