# Generated by Django 3.2 on 2023-03-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_auto_20230307_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
            ],
            options={
                'verbose_name_plural': 'SMS Api Bilgileri',
                'ordering': ['-id'],
            },
        ),
    ]
