# Generated by Django 3.2 on 2023-03-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0007_smsapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettingsnew',
            name='fav_icon',
            field=models.ImageField(default='af', upload_to='', verbose_name='Fav İcon'),
            preserve_default=False,
        ),
    ]
